<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\images\Logo_Soteria.jpg" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Soteria.Sql\Soteria.Sql.csproj" />
    <ProjectReference Include="..\Soteria.UI.Shared\Soteria.UI.Shared.csproj" />
  </ItemGroup>

</Project>
